config/routes.rb
Rails4version::Application.routes.draw do
  resources :doctors

  resources :departments

  resources :patients

  get "page/index"
  get "page/user"
  get "page/patient"

  root 'page#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all


    @json = @departments.to_json(
        :only =>[:id,:name]
    )

    respond_to do |format|
      format.json { render :json => @json }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render action: 'show', status: :created, location: @department }
      else
        format.html { render action: 'new' }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
   puts '--------------------------'
   puts params
   @doctors
    if params[:department_id]
      @doctors =Doctor.where(:deparment_id => params[:department_id] )
    else
      @doctors = Doctor.all
    end

   puts '---------------------------'


   @json = @doctors.to_json(
       :only =>[:id,:name]
   )

   respond_to do |format|
     format.json { render :json => @json }
   end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor }
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :deparment_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def user
    render  :text => "{  success: true,users: [ {id: 1, name: 'Ed padsdk',    email: 'ed ward @sencha.com'}, {id: 2, name: 'Tommy', email: 'tommy@sencha.com'}   ]} "
  end


  def patient
    render  :text => "{  success: true,patients: [ {patient_ids: 1, name: 'Ed padsdk',    spell_code: 'ed ward @sencha.com'}, {patient_ids: 2, name: 'Tommy', spell_code: 'tommy@sencha.com'}   ]} "
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => :index
  skip_before_filter :verify_authenticity_token
  respond_to :js
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    respond_with(@patients) do |format|
      format.json {render  :json =>@patients ,:id =>true }
      #format.as_json(include: :id)
    end


  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
     puts "-------------------------------------------------"
     puts patient_params
     puts "-------------------------------------------------"

    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        #format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
        #format.json { render json: { success: true, data: "succ" } }
      else
        #format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
        #format.json { render json: { success: false, errors: user.errors } }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        #format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        #format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:patient_ids, :spell_code, :name, :social_security_number, :sex, :birthday, :residence, :nationality, :citizenship, :photo, :education, :household, :occupation, :orgnization, :orgnization_address, :mobile_phone, :home_phone, :home_address, :contact, :contact_phone, :habitual_type, :marital_status, :insurance_type, :insurance_number, :blood_type, :allergy_history, :vaccination_history, :disease_history, :heredopathia_history, :health_risk_factor, :is_handicapped, :handicap_card_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :deparment_id %><br>
    <%= f.number_field :deparment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deparment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.deparment_id %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Deparment:</strong>
  <%= @doctor.deparment_id %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4version</title>
  <%= stylesheet_link_tag    "application"%>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "/extjs4/ext-all.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<%= javascript_include_tag "app/app" %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_ids %><br>
    <%= f.text_field :patient_ids %>
  </div>
  <div class="field">
    <%= f.label :spell_code %><br>
    <%= f.text_field :spell_code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :social_security_number %><br>
    <%= f.text_field :social_security_number %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :residence %><br>
    <%= f.text_field :residence %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality %>
  </div>
  <div class="field">
    <%= f.label :citizenship %><br>
    <%= f.text_field :citizenship %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :household %><br>
    <%= f.text_field :household %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :orgnization %><br>
    <%= f.text_field :orgnization %>
  </div>
  <div class="field">
    <%= f.label :orgnization_address %><br>
    <%= f.text_field :orgnization_address %>
  </div>
  <div class="field">
    <%= f.label :mobile_phone %><br>
    <%= f.text_field :mobile_phone %>
  </div>
  <div class="field">
    <%= f.label :home_phone %><br>
    <%= f.text_field :home_phone %>
  </div>
  <div class="field">
    <%= f.label :home_address %><br>
    <%= f.text_field :home_address %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :habitual_type %><br>
    <%= f.text_field :habitual_type %>
  </div>
  <div class="field">
    <%= f.label :marital_status %><br>
    <%= f.text_field :marital_status %>
  </div>
  <div class="field">
    <%= f.label :insurance_type %><br>
    <%= f.text_field :insurance_type %>
  </div>
  <div class="field">
    <%= f.label :insurance_number %><br>
    <%= f.text_field :insurance_number %>
  </div>
  <div class="field">
    <%= f.label :blood_type %><br>
    <%= f.text_field :blood_type %>
  </div>
  <div class="field">
    <%= f.label :allergy_history %><br>
    <%= f.text_field :allergy_history %>
  </div>
  <div class="field">
    <%= f.label :vaccination_history %><br>
    <%= f.text_field :vaccination_history %>
  </div>
  <div class="field">
    <%= f.label :disease_history %><br>
    <%= f.text_field :disease_history %>
  </div>
  <div class="field">
    <%= f.label :heredopathia_history %><br>
    <%= f.text_field :heredopathia_history %>
  </div>
  <div class="field">
    <%= f.label :health_risk_factor %><br>
    <%= f.text_field :health_risk_factor %>
  </div>
  <div class="field">
    <%= f.label :is_handicapped %><br>
    <%= f.check_box :is_handicapped %>
  </div>
  <div class="field">
    <%= f.label :handicap_card_number %><br>
    <%= f.text_field :handicap_card_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Patient ids</th>
      <th>Spell code</th>
      <th>Name</th>
      <th>Social security number</th>
      <th>Sex</th>
      <th>Birthday</th>
      <th>Residence</th>
      <th>Nationality</th>
      <th>Citizenship</th>
      <th>Photo</th>
      <th>Education</th>
      <th>Household</th>
      <th>Occupation</th>
      <th>Orgnization</th>
      <th>Orgnization address</th>
      <th>Mobile phone</th>
      <th>Home phone</th>
      <th>Home address</th>
      <th>Contact</th>
      <th>Contact phone</th>
      <th>Habitual type</th>
      <th>Marital status</th>
      <th>Insurance type</th>
      <th>Insurance number</th>
      <th>Blood type</th>
      <th>Allergy history</th>
      <th>Vaccination history</th>
      <th>Disease history</th>
      <th>Heredopathia history</th>
      <th>Health risk factor</th>
      <th>Is handicapped</th>
      <th>Handicap card number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.patient_ids %></td>
        <td><%= patient.spell_code %></td>
        <td><%= patient.name %></td>
        <td><%= patient.social_security_number %></td>
        <td><%= patient.sex %></td>
        <td><%= patient.birthday %></td>
        <td><%= patient.residence %></td>
        <td><%= patient.nationality %></td>
        <td><%= patient.citizenship %></td>
        <td><%= patient.photo %></td>
        <td><%= patient.education %></td>
        <td><%= patient.household %></td>
        <td><%= patient.occupation %></td>
        <td><%= patient.orgnization %></td>
        <td><%= patient.orgnization_address %></td>
        <td><%= patient.mobile_phone %></td>
        <td><%= patient.home_phone %></td>
        <td><%= patient.home_address %></td>
        <td><%= patient.contact %></td>
        <td><%= patient.contact_phone %></td>
        <td><%= patient.habitual_type %></td>
        <td><%= patient.marital_status %></td>
        <td><%= patient.insurance_type %></td>
        <td><%= patient.insurance_number %></td>
        <td><%= patient.blood_type %></td>
        <td><%= patient.allergy_history %></td>
        <td><%= patient.vaccination_history %></td>
        <td><%= patient.disease_history %></td>
        <td><%= patient.heredopathia_history %></td>
        <td><%= patient.health_risk_factor %></td>
        <td><%= patient.is_handicapped %></td>
        <td><%= patient.handicap_card_number %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient ids:</strong>
  <%= @patient.patient_ids %>
</p>

<p>
  <strong>Spell code:</strong>
  <%= @patient.spell_code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Social security number:</strong>
  <%= @patient.social_security_number %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @patient.sex %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @patient.birthday %>
</p>

<p>
  <strong>Residence:</strong>
  <%= @patient.residence %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @patient.nationality %>
</p>

<p>
  <strong>Citizenship:</strong>
  <%= @patient.citizenship %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @patient.photo %>
</p>

<p>
  <strong>Education:</strong>
  <%= @patient.education %>
</p>

<p>
  <strong>Household:</strong>
  <%= @patient.household %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @patient.occupation %>
</p>

<p>
  <strong>Orgnization:</strong>
  <%= @patient.orgnization %>
</p>

<p>
  <strong>Orgnization address:</strong>
  <%= @patient.orgnization_address %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @patient.mobile_phone %>
</p>

<p>
  <strong>Home phone:</strong>
  <%= @patient.home_phone %>
</p>

<p>
  <strong>Home address:</strong>
  <%= @patient.home_address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @patient.contact %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @patient.contact_phone %>
</p>

<p>
  <strong>Habitual type:</strong>
  <%= @patient.habitual_type %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @patient.marital_status %>
</p>

<p>
  <strong>Insurance type:</strong>
  <%= @patient.insurance_type %>
</p>

<p>
  <strong>Insurance number:</strong>
  <%= @patient.insurance_number %>
</p>

<p>
  <strong>Blood type:</strong>
  <%= @patient.blood_type %>
</p>

<p>
  <strong>Allergy history:</strong>
  <%= @patient.allergy_history %>
</p>

<p>
  <strong>Vaccination history:</strong>
  <%= @patient.vaccination_history %>
</p>

<p>
  <strong>Disease history:</strong>
  <%= @patient.disease_history %>
</p>

<p>
  <strong>Heredopathia history:</strong>
  <%= @patient.heredopathia_history %>
</p>

<p>
  <strong>Health risk factor:</strong>
  <%= @patient.health_risk_factor %>
</p>

<p>
  <strong>Is handicapped:</strong>
  <%= @patient.is_handicapped %>
</p>

<p>
  <strong>Handicap card number:</strong>
  <%= @patient.handicap_card_number %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>